name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v4.1.7

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4.0.1
          with:
            dotnet-version: 8.x

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish WitchSaga.Web.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: bin\release\net8.0\publish
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
